# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variantschema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13variantschema.proto\x12\x06models\"\xd8\x01\n\x07Variant\x12\x12\n\nchromosome\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x11\n\treference\x18\x03 \x01(\t\x12\x11\n\talternate\x18\x04 \x01(\t\x12\x0e\n\x06\x66ilter\x18\x05 \x01(\t\x12\x0c\n\x04info\x18\x06 \x01(\t\x12\x31\n\tgenotypes\x18\x07 \x03(\x0b\x32\x1e.models.Variant.GenotypesEntry\x1a\x30\n\x0eGenotypesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')



_VARIANT = DESCRIPTOR.message_types_by_name['Variant']
_VARIANT_GENOTYPESENTRY = _VARIANT.nested_types_by_name['GenotypesEntry']
Variant = _reflection.GeneratedProtocolMessageType('Variant', (_message.Message,), {

  'GenotypesEntry' : _reflection.GeneratedProtocolMessageType('GenotypesEntry', (_message.Message,), {
    'DESCRIPTOR' : _VARIANT_GENOTYPESENTRY,
    '__module__' : 'variantschema_pb2'
    # @@protoc_insertion_point(class_scope:models.Variant.GenotypesEntry)
    })
  ,
  'DESCRIPTOR' : _VARIANT,
  '__module__' : 'variantschema_pb2'
  # @@protoc_insertion_point(class_scope:models.Variant)
  })
_sym_db.RegisterMessage(Variant)
_sym_db.RegisterMessage(Variant.GenotypesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VARIANT_GENOTYPESENTRY._options = None
  _VARIANT_GENOTYPESENTRY._serialized_options = b'8\001'
  _VARIANT._serialized_start=32
  _VARIANT._serialized_end=248
  _VARIANT_GENOTYPESENTRY._serialized_start=200
  _VARIANT_GENOTYPESENTRY._serialized_end=248
# @@protoc_insertion_point(module_scope)
